name: Yak Publish
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Build
        run: dotnet build src/Numbat/Numbat/Numbat.csproj -c Release

      - name: Copy files to Release folders
        shell: pwsh
        run: |
          Copy-Item assets/brand/numbat-icon-512.png src/Numbat/Numbat/bin/Release/net7.0/numbat-icon-512.png
          Copy-Item assets/brand/numbat-icon-512.png src/Numbat/Numbat/bin/Release/net48/numbat-icon-512.png
          Copy-Item src/Numbat/Numbat/manifest.yml src/Numbat/Numbat/bin/Release/net7.0/manifest.yml
          Copy-Item src/Numbat/Numbat/manifest.yml src/Numbat/Numbat/bin/Release/net48/manifest.yml

      - name: Set version in manifest
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}".TrimStart('v')
          (Get-Content src/Numbat/Numbat/bin/Release/net7.0/manifest.yml) -replace '\$version', $version | Set-Content src/Numbat/Numbat/bin/Release/net7.0/manifest.yml

      - name: Download Yak
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://files.mcneel.com/yak/tools/latest/yak.exe" -OutFile "${{ github.workspace }}/yak.exe"

      - name: Yak Build and Push
        shell: pwsh
        working-directory: src/Numbat/Numbat/bin/Release/net7.0
        env:
          YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
        run: |
          & "${{ github.workspace }}/yak.exe" build
          $yakFile = (Get-Item *.yak).Name
          & "${{ github.workspace }}/yak.exe" push $yakFile