name: Yak Publish
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Build
        run: dotnet build src/Lichen/Lichen/Lichen.csproj -c Release

      - name: Copy files to Release folders
        run: |
          cp assets/brand/lichen-icon-512.png src/Lichen/Lichen/bin/Release/net7.0/lichen-icon-512.png
          cp assets/brand/lichen-icon-512.png src/Lichen/Lichen/bin/Release/net48/lichen-icon-512.png
          cp src/Lichen/Lichen/manifest.yml src/Lichen/Lichen/bin/Release/net7.0/manifest.yml
          cp src/Lichen/Lichen/manifest.yml src/Lichen/Lichen/bin/Release/net48/manifest.yml

      - name: Set version in manifest
        run: |
          $version = "${{ github.ref_name }}".TrimStart('v')
          (Get-Content src/Lichen/Lichen/bin/Release/net7.0/manifest.yml) -replace '\$version', $version | Set-Content src/Lichen/Lichen/bin/Release/net7.0/manifest.yml
        shell: pwsh

      - name: Download Yak
        run: Invoke-WebRequest -Uri "https://files.mcneel.com/yak/tools/latest/yak.exe" -OutFile "${{ github.workspace }}/yak.exe"
        shell: pwsh

      - name: Yak Build and Push
        run: |
          & "${{ github.workspace }}/yak.exe" build
          $yakFile = (Get-Item *.yak).Name
          & "${{ github.workspace }}/yak.exe" push $yakFile
        working-directory: src/Lichen/Lichen/bin/Release/net7.0
        env:
          YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
        shell: pwsh
